### ISSUE TITLE
Souder la quantité minimale de boards du BMS

### ISSUE THREAD

**Issue by oclarocque** [EclipseETS/E10-BMS-HW#3]
Une 2e version des boards (master, slave et current sense) a été fabriquée. On devra souder minimalement 1 master, 4 slaves et 1 current sense étant donné la configuration de 13p32s du battery pack d'Éclipse 10.

- [x] Master

- [x] Slave 1

- [x] Slave 2

- [x] Slave 3

- [x] Slave 4

- [x] Current Sense

**Comment by chrisdsa** [comment]
Voir la commande Digikey : http://www.digikey.com/short/q3q1j3
Trouver des alternatives aux pieces out of stock

**Comment by chrisdsa** [comment]
Reste a modifier la commande
