### ISSUE TITLE
Mush sur le master

### ISSUE THREAD

**Issue by jfchenier** [EclipseETS/E10-BMS-HW#4]
Dans la révision B des règlement de la ASC, un nouveau règlement est apparu

8.6.C.4 Operation: To operate the external actuator, it must require only a single simple action such as
‘push’, ‘pull’ or ‘twist’ etc. External actuator must also illuminate the BPS Fault indication including BPS
Fault Dash Indicator.

Cela veux dire que le mush ne peut pas killer la voiture au complet. Christian et moi avons conclu qu'étant donné que nous devons faire une révision 3 du Master nous devripons mettre le mush directement sur l'alimentation des relais. Dans le cas d'un appuie sur le mush les relais s'ouvernt et le power supply switch automatiquement l'allimentation sur la batterie auxiliaire.

**Comment by P-OMeilleur** [comment]
Features implémenté sur la V3 du master E10
